
kind: PersistentVolume
apiVersion: v1beta3
metadata:
  # Name is unique within a namespace.  Name is required when creating resources, although
  # some resources may allow a client to request the generation of an appropriate name
  # automatically. Name is primarily intended for creation idempotence and configuration
  # definition.
  # 
  # String that identifies an object. Must be unique within a namespace; 
  # Cannot be updated.
  name: repository-volume

  # Namespace defines the space within which name must be unique. An empty namespace is
  # equivalent to the "default" namespace, but "default" is the canonical representation.
  # Not all objects are required to be scoped to a namespace - the value of this field for
  # those objects will be empty.
  namespace: repository

  # Labels are key value pairs that may be used to scope and select individual resources.
  labels:
    name: repository-volume

# Spec defines the behavior of a pod
spec:

  # A description of the persistent volume's resources and capacity.
  capacity:

    # Volume size, in bytes (e,g. 5Gi = 5GiB = 5 * 1024 * 1024 * 1024)
    storage: 

  # HostPath represents a directory on the host.
  # This is useful for development and testing only.
  # on-host storage is not supported in any way.
  hostPath: 

    # Path of the directory on the host.
    path: 

  # AccessModes contains all ways the volume can be mounted
  accessModes: 
    - ReadWriteOnce
    - ReadOnlyMany

  # Holds the binding reference to a PersistentVolumeClaim
  claimRef: repository-volume-claim













