
kind: Service
apiVersion: v1beta3
metadata:
  # Name is unique within a namespace.  Name is required when creating resources, although
  # some resources may allow a client to request the generation of an appropriate name
  # automatically. Name is primarily intended for creation idempotence and configuration
  # definition.
  # 
  # String that identifies an object. Must be unique within a namespace; 
  # Cannot be updated.
  name: 

  # GenerateName indicates that the name should be made unique by the server prior to persisting
  # it. A non-empty value for the field indicates the name will be made unique (and the name
  # returned to the client will be different than the name passed). The value of this field will
  # be combined with a unique suffix on the server if the Name field has not been provided.
  # The provided value must be valid within the rules for Name, and may be truncated by the length
  # of the suffix required to make the value unique on the server.
  #
  # If this field is specified, and Name is not present, the server will NOT return a 409 if the
  # generated name exists - instead, it will either return 201 Created or 500 with Reason
  # ServerTimeout indicating a unique name could not be found in the time allotted, and the client
  # should retry (optionally after the time indicated in the Retry-After header).
  generateName:

  # Namespace defines the space within which name must be unique. An empty namespace is
  # equivalent to the "default" namespace, but "default" is the canonical representation.
  # Not all objects are required to be scoped to a namespace - the value of this field for
  # those objects will be empty.
  namespace:

  # Labels are key value pairs that may be used to scope and select individual resources.
  labels:
    name: value

  # Annotations are unstructured key value data stored with a resource that may be set by
  # external tooling. They are not queryable and should be preserved when modifying
  # objects.
  annotations:
    name: value

# Spec defines the behavior of a service.
spec: 

  # Required: The list of ports that are exposed by this service.
  ports: 

      # Optional if only one ServicePort is defined on this service: The
      # name of this port within the service.  This must be a DNS_LABEL.
      # All ports within a ServiceSpec must have unique names.  This maps to
      # the 'Name' field in EndpointPort objects.
    - name:

      # The protocol used by this port; must be UDP or TCP; TCP if unspecified.
      protocol:

      # The port that will be exposed by this service.
      port: 

      # Optional: The target port on pods selected by this service.
      # If this is a string, it will be looked up as a named port in the
      # target Pod's container ports.  If this is not specified, the value
      # of Port is used (an identity map).
      targetPort:

  # This service will route traffic to pods having labels matching this selector. 
  # If null, no endpoints will be automatically created. If empty, all pods will be selected.
  selector: 
    key: value

  # PortalIP is usually assigned by the master.  If specified by the user
  # we will try to respect it or else fail the request.  This field can
  # not be changed by updates.
  # Valid values are None, empty string (""), or a valid IP address
  # None can be specified for headless services when proxying is not required.
  portalIP:

  # Set up a cloud-provider-specific load balancer on an external IP.
  createExternalLoadBalancer: false

  # PublicIPs are used by external load balancers, or can be set by
  # users to handle external traffic that arrives at a node.
  publicIPs: []

  # Optional: Supports "ClientIP" and "None".  Used to maintain session affinity.
  sessionAffinity: ClientIP





