# Service for load balancing frontend component
kind: Service
apiVersion: v1beta3
metadata:
  name: phpfpm
  labels:
    name: phpfpm
spec:
  # Expose service to http (not important as wil be handled by reverse-proxy)
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP

  # Match any phpfpm pod
  selector:
    name: phpfpm
  # Any SSL requests will be terminated in the pods. Because of this we need to 
  # enable routing users to the correct pod to correctly handle SSL sessions
  sessionAffinity: ClientIP